name: spef
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
  fonts:
    - family: Poppins
    #-  fonts:
       # - asset: fonts/Schyler-Regular.ttf
          # style: italic  # if you don't need italic variant
    # Add additional font families here if needed
